// Description:
//   Send insults generated by https://www.wowbagger.com/process.php.
//
// Dependencies:
//   "fs": "0.0.1-security"
//   "node-html-parser": "1.1.10"
//   "request": "2.88.0"
//
// Commands:
//   marvin - Send an insult
//   hubot debug:insults - Respond with the current state of the Prefetchedstream

fs = require("fs");
request = require("request");
parser = require("node-html-parser");

class PrefetchedStream {
  constructor(sourceAsync, seed = [], maxBackups) {
    this.sourceAsync = sourceAsync;
    this.prefetched = seed;
    this.backups = [];
    this.maxBackups = maxBackups || 20;
  }

  next() {
    if (this.prefetched.length === 0) {
      return randomElement(this.backups);
    }

    const elt = this.prefetched.pop();
    this.sourceAsync(elt => this.prefetched.push(elt));
    this.addToBackups(elt);
    return elt;
  }

  addToBackups(elt) {
    this.backups.push(elt);
    if (this.backups.length > this.maxBackups) {
      this.elt.pop();
    }
  }
}

function randomElement(items) {
  return items[Math.floor(Math.random() * items.length)];
}

function extractInsult(page) {
  const root = parser.parse(page);
  return root.querySelector(".customBig").structuredText;
}

function fetchInsult(cb) {
  request.get("https://www.wowbagger.com/process.php", function(
    error,
    response,
    body
  ) {
    cb(extractInsult(body));
  });
}

const initial = fs
  .readFileSync("resources/insults.txt", "utf-8")
  .split("\n")
  .filter(s => s !== "");

const insults = new PrefetchedStream(fetchInsult, initial, 100);

module.exports = function(robot) {
  robot.respond(/debug:insults/, res => {
    res.reply(`backups: ${insults.backups}\nprefetched: ${insults.prefetched}`);
  });
  robot.hear(/marvin\??/gi, res => {
    res.send(insults.next());
  });
};
